Visualisation/Models/CovidCsvModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Visualisation.Models
{
	public class CovidCsvModel
	{
		public DateTime Date_reported { get; set; }
		public string Country_code { get; set; }
		public string Country { get; set; }
		public string WHO_region { get; set; }
		public double New_cases { get; set; }
		public double Cumulative_cases { get; set; }
		public double New_deaths { get; set; }
		public double Cumulative_deaths { get; set; }
	}
}

Visualisation/Models/ErrorViewModel.cs
using System;

namespace Visualisation.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Visualisation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Visualisation.Models;

namespace Visualisation.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Visualisation/Controllers/VisualisationController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Visualisation.Abstractions;
using Visualisation.Models;

namespace Visualisation.Controllers
{
	public class VisualisationController : Controller
	{
		private IEnumerable<CovidCsvModel> CovidList;
		private readonly ICsvService _csvService;
		private readonly IWebHostEnvironment _environment;
		private readonly IMapCalculations _mapCalculations;
		private readonly ICharts _charts;
		public VisualisationController(IWebHostEnvironment environment, ICsvService csvService, ICharts charts, IMapCalculations mapCalculations)
		{
			_environment = environment;
			_csvService = csvService;
			_charts = charts;
			_mapCalculations = mapCalculations;
			string fullPath = Path.Combine(_environment.WebRootPath, "csv", "COVID-global-data.csv");
			CovidList = _csvService.ReadCsv(fullPath);
			//string filePath = Path.Combine(_environment.WebRootPath, "js", "mapData.js");
			//_mapCalculations.CreateJSFileCovidCases(CovidList.ToList(), filePath);
		}
		[HttpGet]
		public IActionResult Index()
		{
			List<CovidCsvModel> covidListCasesNow = new List<CovidCsvModel>();
			double allCases = 0;
			foreach (var CountryLastRecord in CovidList
				.OrderByDescending(x => x.Date_reported)
				.Where(x => x.Date_reported == CovidList.OrderByDescending(x => x.Date_reported).Select(x => x.Date_reported).FirstOrDefault())
				.Take(235))
			{
				covidListCasesNow.Add(CountryLastRecord);
				allCases += CovidList.OrderByDescending(x => x.Date_reported).Where(x => x.Country == CountryLastRecord.Country).FirstOrDefault().Cumulative_cases;
			}
			ViewData["WorldCases"] = allCases.ToString();
			return View(covidListCasesNow);
		}
        [HttpGet]
        public IActionResult PolishChart()
        {
			List<double?> covidData1 = new List<double?>();
            covidData1.AddRange(CovidList.OrderBy(x => x.Date_reported).Where(x => x.Country_code == "PL").Select(x => (double?)x.Cumulative_cases));
			List<double?> covidData2 = new List<double?>();
			covidData2.AddRange(CovidList.OrderBy(x => x.Date_reported).Where(x => x.Country_code == "PL").Select(x => (double?)x.Cumulative_deaths));
			List<string> Days = new List<string>();
            foreach (var Day in CovidList.OrderBy(x => x.Date_reported).Where(x => x.Country_code == "PL").Select(x => x.Date_reported.ToShortDateString()))
            {
                Days.Add(Day.ToString());
            }
            ViewData[$"PolishCases"] = _charts.getDoubleLineChart(covidData1, covidData2, Days, "Polish Cumulative Cases", "Polish Cumulative Deaths");

			return View();
        }
		public IActionResult EuropeChart()
		{
			List<double?> covidData1 = new List<double?>();
			foreach (var euCases in CovidList
				.OrderByDescending(x => x.Date_reported)
				.Where(x => x.WHO_region == "EURO" && x.Date_reported == CovidList.OrderByDescending(x => x.Date_reported).Select(x => x.Date_reported).FirstOrDefault())
				.Select(x => x.Cumulative_cases)
				.Take(53))
			{
				covidData1.Add(euCases);
			}
			List<double?> covidData2 = new List<double?>();
			foreach (var euDeaths in CovidList
				.OrderByDescending(x => x.Date_reported)
				.Where(x => x.WHO_region == "EURO" && x.Date_reported == CovidList.OrderByDescending(x => x.Date_reported).Select(x => x.Date_reported).FirstOrDefault())
				.Select(x => x.Cumulative_deaths)
				.Take(53))
			{
				covidData2.Add(euDeaths);
			}
			List<string> Countries = new List<string>();
			foreach (var country in CovidList
				.OrderByDescending(x => x.Date_reported)
				.Where(x => x.WHO_region == "EURO" && x.Date_reported == CovidList.OrderByDescending(x => x.Date_reported).Select(x => x.Date_reported).FirstOrDefault())
				.Select(x => x.Country)
				.Take(53))
			{
				Countries.Add(country.ToString());
			}
			ViewData[$"EuropeChart"] = _charts.getDoubleBarChart(covidData1, covidData2, Countries, "Europe Cumulative Cases", "Europe Cumulative Deaths");

			return View();
		}
    }
}

Visualisation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Visualisation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Visualisation</title>
	<!-- Bootstrap core CSS -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
	<!-- Material Design Bootstrap -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
	<link href="~/lib/jvectormap/jquery-jvectormap-2.0.5.css" rel="stylesheet" />
	<link href="~/lib/chart.js-2.8.0/dist/Chart.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Visualisation" asp-action="index">Home</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Visualisation" asp-action="PolishChart">Poland</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Visualisation" asp-action="EuropeChart">Europe</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - Visualisation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/chart.js-2.8.0/dist/Chart.js"></script>
	<script src="~/lib/jvectormap/jquery-jvectormap-2.0.5.min.js"></script>
	<script src="~/lib/jvectormap/jquery-jvectormap-world-mill.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Visualisation/Views/Visualisation/EuropeChart.cshtml
@model IEnumerable<CovidCsvModel>
@{
    ViewData["Title"] = "Europes";
}

<div class="container fluid">
    <div class="row">
        <div class="offset-1 col-10 text-center">
            <br />
            <h2> <i class="fas fa-tint mb-3 mr-3"></i>Europe</h2>
            <hr />
            <br />
        </div>
        <div class="offset-1 col-10 algin-left">
            <h5>
                Chart with cumulutive  cases and deaths for Europe. <br />
                After hovering over the bar, it shows specific numbers.
            </h5>

            <canvas id="EuropeChart"></canvas>

        </div>
    </div>
</div>


@{ChartJSCore.Models.Chart EuropeChart = (ChartJSCore.Models.Chart)ViewData["EuropeChart"]; }
@section Scripts {
    <script>
        @Html.Raw(EuropeChart.CreateChartCode("EuropeChart"));
    </script>
}

Visualisation/Views/Visualisation/Index.cshtml
@model IEnumerable<Visualisation.Models.CovidCsvModel>

@{
	ViewData["Title"] = "World";
}

<div class="container">
    <div class="container mt-4" id="section-interests">
        <div class="row">
            <div class="col ml-3 mr-3">
                <h1 style="text-align:center">World</h1>
                <hr />
            </div>
        </div>
       
        <div class="row">
            <div>
                <h5>Map with cumulutive cases in the world. </h5>
                <h5>Total number of infections in the world is about <b>@ViewData["WorldCases"]</b></h5>
            </div>
            <div id="world-map" style="width: 100%; height: 550px"></div>
        </div>
        <br />
        <h5> Table for all countries with cases and deaths </h5>
        <br />
        <div class="row">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>
                            Country code
                        </th>
                        <th>
                            Code
                        </th>
                        <th>
                            Cases
                        </th>
                        <th>
                            Deaths
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Country_code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Country)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cumulative_cases)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cumulative_deaths)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/js/mapData.js"></script>
@section Scripts {
	<script>
		$(function () {
			$('#world-map').vectorMap({
				map: 'world_mill',
				series: {
					regions: [{
						values: covidData,
						scale: ['#FFFFFF', '#DC143C'],
						normalizeFunction: 'polynomial'
					}]
				}
			});
		});
	</script>
}

Visualisation/Views/Visualisation/PolishChart.cshtml
@model IEnumerable<CovidCsvModel>
@{
	ViewData["Title"] = "Poland";
}

<div class="container fluid">
	<div class="row">
		<div class="offset-1 col-10 text-center">
			<br />
			<h2> <i class="fas fa-tint mb-3 mr-3"></i>Poland</h2>
			<hr />
			<br />
		</div>
        <div class="offset-1 col-10 algin-left">
            <h5>
                Chart with cumulutive cases and deaths for Poland. <br />
                After hovering over the line, it shows specific numbers.
            </h5>

            <canvas id="PolishCases"></canvas>

        </div>
	</div>
</div>


@{ChartJSCore.Models.Chart PolishCases = (ChartJSCore.Models.Chart)ViewData["PolishCases"]; }
@section Scripts {
	<script>
        @Html.Raw(PolishCases.CreateChartCode("PolishCases"));
	</script>
}